### PR TITLE
Get rid of after commit deprecation warning

### PR DESCRIPTION
**Pull request by eugenk**
Devise 4.3.0 confirmable module uses hooks like

```ruby
after_commit :send_on_create_confirmation_instructions, on: :create, if: :send_confirmation_notification?
after_commit :send_reconfirmation_instructions, on: :update, if: :reconfirmation_required?
```
which invoke this deprecation warning of Sequel:
```
SEQUEL DEPRECATION WARNING: Sequel::Model.after_commit in the hook_class_methods plugin is deprecated and will be removed in Sequel 5.  Use after_save{db.after_commit{}} instead.
```

This pull request uses the recommended code for `after_commit` and allows to use the `:on` option.

I hope it's okay that I bumped the version.

### CODE REVIEW

**Comment by rosenfeld** [comment]
Hi, Eugen, thanks for the PR. I'm no longer using Devise and I have no interest in maintaining this project. So, I'd like to ask if you'd like to maintain it. If you want to, just let me know your credentials in RubyGems and I'll make sure to add you as a team member as soon as I figure out how to do that. Then you have two options. I can add you as a contributor to this repository and you can use it as you want, or you could fork it and I can change the README in this repository to point it to its new address. Please let me know what approach you prefer or suggest a new one if you want. Take your time. If you don't want to maintain it at this point I can simply merge your changes and release a new version without testing, but I'd certainly prefer to have you maintaining it.

**Comment by eugenk** [comment]
Thanks for the quick reply! I think it's the easiest if I maintain the project in the fork that I created for this PR. My RubyGems username is `eugenk`.

**Comment by rosenfeld** [comment]
I've added you as a gem owner of sequel-devise and also added you to the Collaborators team so that you can change this project, such as README and description to point to your fork the way you prefer. Thank you very much!

**Comment by eugenk** [comment]
Thanks! I will change it accordingly. And thank you for the code base 👍

**Comment by rosenfeld** [comment]
You're welcome :)

**Comment by eugenk** [comment]
All done.

**Comment by rosenfeld** [comment]
Thank you, Eugen! This was a good birthday gift :)

**Comment by eugenk** [comment]
Well, happy birthday! =D

**Comment by rosenfeld** [comment]
Thank you :) Not sure if this is something we should celebrate anyway :D

**Pull request closed without merging**
